name: update

on:
  workflow_dispatch:
  schedule:
    # 日本時間午前4時（深夜帯に更新されがちなので）
    - cron: '0 19 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Set branch name as environment variable
        run: echo "NEW_BRANCH_NAME=update-og-images-$(date '+%s')" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup deno
        uses: denoland/setup-deno@v2.0.4
        with:
          deno-version: 2.x

      - name: Recreate image list
        run: deno task update

      - name: Create pull request
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: 🍱 og-imageを更新
          branch: ${{ env.NEW_BRANCH_NAME }}
          delete-branch: true
          title: "🍱 og-imageを更新"
          body: "このPRは自動生成されました 🤖"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
